version: '3.9'

services:
  model:
    build: ./build/
    restart: always
    ports:
      - "7860:7860"
    volumes:
      - ./cache:/cache
      - ./output:/output
      - ./models:/models
    environment:
      - CLI_ARGS=--outdir /output --save-metadata --ckpt /models/model.ckpt
      #--extra-models-cpu --optimized
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
